### ISSUE TITLE
Two Drawers, Slack style

### ISSUE THREAD

**Issue by ryanmcdermott** [root-two/react-native-drawer#32] opened 2015-10-06 19:05 UTC
How would you go about having two drawers, Slack style? In Slack there's a left and a right drawer that both can pop out. When trying it with `react-native-drawer` I had trouble getting them on their own respective sides. I used the `side` property with one on left and one on right but it didn't end up working.

**Comment by rt2zz** [comment] 2015-10-07 21:09
Did you get an error, or did one of the drawers not work?

**Comment by ryanmcdermott** [comment] 2015-10-08 02:38
One of the drawers didn't work. When I put the drawers side by side (one with `side: 'left'` and one with `side: 'right'`) all inside in an enclosing `<View>` it just showed both on the left.

**Comment by rt2zz** [comment] 2015-10-10 23:11
Ah, I think the problem is you may have put the drawers as siblings, when they should actual be nested. EG

``` js
<Drawer
  type='static'
  openDrawerOffset={100}
  side='left'
  content={<ControlPanelRoot />}
  >
  <Drawer
    type='static'
    openDrawerOffset={100}
    side='right'
    content={<ControlPanelRoot />}
    >  
    <MainContent />
  </Drawer>
</Drawer>
```

Let me know if that fixes it for you

**Comment by rt2zz** [comment] 2015-10-16 22:10
@ryanmcdermott this should be fixed, let me know if it does not work for you

**Closed as completed by rt2zz** 2015-10-16 22:10 UTC
