### ISSUE TITLE
Two Drawers - onClose not firing on touch event

### ISSUE THREAD

**Issue by rgoldiez** [root-two/react-native-drawer#50] opened 2015-11-25 11:07 UTC
I'm new to this package so forgive me if I don't have it setup properly.  I'm trying to create a left and right drawer, which I have nested as suggested in an older issue.  

It appears through some debugging that a dragged touch to close either panel below does **not** fire the onClose handler.  I have a custom nav bar with a left and right button; those buttons call the open/close methods as shown below and the button press method **does** cause the appropriate drawer to fire it's onClose handler.  In fact, it looks like it's firing onOpen of the other drawer.

Any suggestions?

```
toggleLeftDrawer: function() {
   (this.state.leftDrawerOpen) ? this.refs.leftDrawer.close() : this.refs.leftDrawer.open();
},
toggleRightDrawer: function() {
   (this.state.rightDrawerOpen) ? this.refs.rightDrawer.close() : this.refs.rightDrawer.open();
}

<Drawer
   ref='leftDrawer'
   type='static'
   side='left'
   content={<Text>Left Panel</Text>}
   openDrawerOffset={100}
   onOpen={this.openLeftDrawer}
   onClose={this.closeDrawer}
   styles={{main: {shadowColor: '#000000', shadowOpacity: 0.4, shadowRadius: 3}}}
   tweenHandler={Drawer.tweenPresets.parallax}
   >
   <Drawer
      ref='rightDrawer'
      type='static'
      side='right'
      content={<Text>Right Panel</Text>}
      openDrawerOffset={100}
      onOpen={this.openRightDrawer}
      onClose={this.closeDrawer}
      styles={{main: {shadowColor: '#000000', shadowOpacity: 0.4, shadowRadius: 3}}}
      tweenHandler={Drawer.tweenPresets.parallax}
      >
      <View>
         ...
      </View>
   </Drawer>
</Drawer>
```

**Comment by rt2zz** [comment] 2015-11-25 18:25
Not sure off the top of my head. Are the drawers acting as intended visually, and the only problem is the onClose callback?

**Comment by rt2zz** [comment] 2015-11-27 23:26
The nested drawers are competing for the "pan handler". So what happens is "closing" the drawer is actually never really closing the drawer but instead triggering the "open" of the opposite drawer.

To work around this (for now) you will need to set `captureGestures={true}` for the currently open drawer. Here is a gist showing how that can be done: https://gist.github.com/rt2zz/21d06a70167a6c976f9f

We could solve this internally with a `captureGesturesWhenOpen` prop. the problem is there are already so many props, so I want to think on this for a bit, and am open to suggestions for other solutions.

**Comment by rgoldiez** [comment] 2015-11-28 02:31
Thanks for the help.  I added the captureGestures (as you had it) and I was still having the problems.  I finally figured out that I was on v1.8.0 of react-native-drawer.  Once I upgraded to v1.9.0 those problems went away.  Appreciate the help!

**Comment by Jpadilla1** [comment] 2016-01-31 07:00
@rt2zz I have the same issue. I tried your exact gist and the onClose callback is still not being called. I am using v1.13.0. Debugging your code in the Gist, when opening and closing the left drawer works fine, but when you open the right drawer and then close it, the onOpen callback gets called of the left drawer instead of the onClose callback of the right drawer.

Any updates on this?

**Comment by Jpadilla1** [comment] 2016-02-01 03:24
I got it working modifying the openLeftDrawer function to this.

``` javascript
openLeftDrawer () {
    if (this.state.rightDrawerOpen) {
      this.setState({
        rightDrawerOpen: false,
        leftDrawerOpen: false
      });
      this.refs.leftDrawer.close();
      this.refs.rightDrawer.close();
    } else {
      this.setState({
        leftDrawerOpen: true
      });
    }
  }
```

Note: I am setting negotiatePan to true in my case.

**Comment by mattshaffer11** [comment] 2016-03-16 21:07
@Jpadilla1 Thanks man, this worked really well!

**Comment by mattshaffer11** [comment] 2016-03-18 14:26
As a note here, even with the snippet from Jpadilla1. You will come across some times where swiping repeatedly will cause state issues so that a drawer will be set to open even though it is closed.

To get around this, I disabled panning (aka `acceptPan={false}`) on both drawers and it fixed the issue for me.

**Comment by rt2zz** [comment] 2016-03-18 20:22
In terms of a long term more elegant solution:

I think the fundamental issue here is that the left open pan responder competes with the right close responder. Similarly the right open will compete with the left close. This is actually not trivial to solve because depending on the application which drawer should win (left open vs right close) may vary.

One possible solution here is to have the inner drawer check for the outer drawer context, and if it exists run some disambiguation logic. I think by default we want the "close" responder to win over the "open" responder.

**Comment by rt2zz** [comment] 2016-03-18 21:26
ok I published `@2.0.0-beta2` which has a naive but I think generally acceptable default behavior: when one drawer is open the other drawer is disabled. Currently this only works for 2 drawers, 

Supporting 3+ drawers is possible but will require more work.

**Comment by mattshaffer11** [comment] 2016-03-18 21:42
@rt2zz Awesome, thanks man!

**Comment by rt2zz** [comment] 2016-03-23 00:08
Closing, feel free to reopen if needed

**Closed as completed by rt2zz** 2016-03-23 00:08 UTC
